---
platform: linux

image_resource:
  type: docker-image
  source: {repository: jshingler/hugo}
  # source: {repository: openjdk}

inputs:
    - name: subject
    - name: master-pipeline

outputs:
- name: site

run:
  path: ./master-pipeline/ci/tasks/build.sh
